CREATE TABLE solicitudesMatriculacion (
    id SERIAL PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    nombres VARCHAR(100) NOT NULL,
    provincia_nacimiento VARCHAR(100),
    canton VARCHAR(100),
    genero CHAR(1),
    fecha_nacimiento DATE,
    nacionalidad VARCHAR(100),
    institucion_procede VARCHAR(200),
    representante_nombres VARCHAR(100),
    representante_cedula VARCHAR(20),
    representante_telefono VARCHAR(20),
    representante_profesion VARCHAR(100),
    representante_email VARCHAR(100),
    madre_nombres VARCHAR(100),
    madre_cedula VARCHAR(20),
    madre_telefono VARCHAR(20),
    madre_profesion VARCHAR(100),
    madre_email VARCHAR(100),
    padre_nombres VARCHAR(100),
    padre_cedula VARCHAR(20),
    padre_telefono VARCHAR(20),
    padre_profesion VARCHAR(100),
    padre_email VARCHAR(100),
    provincia_vivienda VARCHAR(100),
    ciudad VARCHAR(100),
    parroquia VARCHAR(100),
    direccion VARCHAR(200),
    telefono_convencional VARCHAR(20),
    latitud DECIMAL(10, 8),
    longitud DECIMAL(11, 8),
    verificado BOOLEAN DEFAULT FALSE
);
